// Generated by CoffeeScript 1.6.2
(function() {
  exports.version = "shadowsocks-nodejs v0.10.0-dev";

  exports.requiredNodeVersion = "0.10.0";

  exports.parseArgs = function() {
    var defination, lastKey, nextIsValue, oneArg, result, _, _ref;

    defination = {
      '-l': 'local_port',
      '-p': 'server_port',
      '-s': 'server',
      '-k': 'password',
      '-c': 'config_file',
      '-m': 'method'
    };
    result = {};
    nextIsValue = false;
    lastKey = null;
    _ref = process.argv;
    for (_ in _ref) {
      oneArg = _ref[_];
      if (nextIsValue) {
        result[lastKey] = oneArg;
        nextIsValue = false;
      } else if (oneArg in defination) {
        lastKey = defination[oneArg];
        nextIsValue = true;
      }
    }
    return result;
  };

  exports.compareVersion = function(l, r) {
    var i, lp, ls, rp, rs, _i, _ref;

    ls = l.split('.');
    rs = r.split('.');
    for (i = _i = 0, _ref = Math.min(ls.length, rs.length); 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      lp = ls[i];
      rp = rs[i];
      if (lp !== rp) {
        return lp - rp;
      }
    }
    return ls.length - rs.length;
  };

  exports.requireVersion = function(version) {
    var nodeVersion;

    nodeVersion = process.versions.node;
    if (exports.compareVersion(nodeVersion, version) < 0) {
      throw new Error("Node version must >= " + version);
    }
  };

  exports.requireVersion(exports.requiredNodeVersion);

}).call(this);
